### PR TITLE
Swift 4 update

### PR DESCRIPTION
**Pull request by pchelnikov**
Solving issue #57

### CODE REVIEW

**Comment by gabek** [comment]
@pchelnikov Awesome, thanks! Could you reflect the version changes in the `.swift-version` and the `README.md`'s Swift Version Badge?

**Comment by pchelnikov** [comment]
@gabek done

**Comment by gabek** [comment]
@pchelnikov I'm seeing a bunch of Swift 4.2 errors when building.

http://f.gabe.bz/efbdfa8d4699

Are you not seeing these errors when you build?

**Comment by pchelnikov** [comment]
@gabek no, I didn't have any problems. But now I set a Swift version explicitly for target. Also I did some proposed by Xcode changes.

Please, try it.

**Comment by gabek** [comment]
Looks good, thanks!

**Pull request merged**
